### ISSUE TITLE
Download link does not work.

### ISSUE THREAD

**Issue by k-allika** [marqdown/marqdown#1]
The download link provided in description does not point to any downloadable file.

**Comment by dev-rke** [comment]
Hi @k-allika,

thanks for the report, i will fix it soon.
In the meantime please use https://marqdown.github.io/ and download from there, also see the "Portable Edition" link in the footer.

**Comment by k-allika** [comment]
> Hi @k-allika,
> 
> thanks for the report, i will fix it soon.
> In the meantime please use https://marqdown.github.io/ and download from there, also see the "Portable Edition" link in the footer.

Thank you for your response. However, the links in  https://marqdown.github.io/ don't work either.
1. The download link does not do anything.
2. The "Portable" link downloads an htm file (the html file of the https://marqdown.github.io page).

**Comment by sitemapxml** [comment]
Hello @k-allika,

> 2. The "Portable" link downloads an htm file (the html file of the https://marqdown.github.io page).

That is actually what you need. That html file is editor, and content from https://marqdown.github.io  is just an example. You can delete all the markdown from the right panel (`ctrl` + `a`, `Del`) and start typing your own. When you finish, just press `Download Markdown` button to download text you were enter, or press `Download HTML` to download rendered html of your text. I hope this will help you!

**Comment by k-allika** [comment]
Ah, cool! I thought I was supposed to download an application (like a .exe file). I get it now. It's a handy tool. Thank you.
